Internal Server Error: /webcam_qr_code_scanner/
Traceback (most recent call last):
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'webcam_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\myapp\views.py", line 87, in webcam_qr_code_scanner
    image_data = request.FILES['webcam_image'].read()
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'webcam_image'
Internal Server Error: /webcam_qr_code_scanner/
Traceback (most recent call last):
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\myapp\views.py", line 109, in webcam_qr_code_scanner
    employee_instance = Employee.objects.get(EmpCode=EmpCode)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
myapp.models.Employee.DoesNotExist: Employee matching query does not exist.
"POST /webcam_qr_code_scanner/ HTTP/1.1" 500 87440
Internal Server Error: /webcam_qr_code_scanner/
Traceback (most recent call last):
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'webcam_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\myapp\views.py", line 89, in webcam_qr_code_scanner
    image_data = request.FILES['webcam_image'].read()
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\VScode files\VPS\django_projects\venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'webcam_image'
